<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <RootNamespace>SarnautCore.Gameplay</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../SarnautCore.Network/SarnautCore.Network.csproj" />
  </ItemGroup>
</Project>
