<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <RootNamespace>SarnautCore.Networking</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.35.1" />
    <PackageReference Include="Grpc.Tools" Version="2.83.0" PrivateAssets="All" />
    <Protobuf Include="Proto\sarnaut\v1\*.proto" ProtoRoot="Proto" GrpcServices="None" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../SarnautCore.NativeHud/SarnautCore.NativeHud.csproj" />
  </ItemGroup>
</Project>
